# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUYM84_ma5PEf4_XJd1h9sBfnurcbqXi
"""

import sys

def cliff_menu():
    print("\nCliff Climbing Game selected.")
    print("Choose algorithm:")
    print("1. SARSA")
    print("2. Q-Learning")
    algo_choice = input("Enter your choice (1 or 2): ").strip()

    if algo_choice == "1":
        import cliff_climbing
        return cliff_climbing.train_sarsa, cliff_climbing.test_sarsa
    elif algo_choice == "2":
        import cliff_climbing
        return cliff_climbing.train_q_learning, cliff_climbing.test_q_learning
    else:
        print("Invalid algorithm choice.")
        sys.exit()

def taxi_menu():
    print("\nTaxi Game selected.")
    import taxi
    return taxi.train_taxi, taxi.test_taxi
def blackjack_menu():
    print("\nBlackjack Game selected.")
    import blackjack
    return blackjack.train_blackjack, blackjack.test_blackjack
def mountaincar_menu():
    print("\nMountainCar Game selected.")
    import mountaincar
    return mountaincar.train_mountaincar, mountaincar.test_mountaincar

def main():
    print("Welcome to the Game Trainer & Tester!")
    print("Select an operation:")
    print("1. Train a game")
    print("2. Test a game")
    operation = input("Enter 1 or 2: ").strip()

    if operation not in ["1", "2"]:
        print("Invalid selection. Exiting.")
        sys.exit()

    print("\nSelect the game:")
    print("1. Cliff Climbing")
    print("2. Taxi")
    print("3. Blackjack")
    print("4. MountainCar")  # <-- add this line

    game_choice = input("Enter game choice (1, 2, 3 or 4): ").strip()

    # game_choice = input("Enter game choice (1, 2 or 3): ").strip()

    # if game_choice == "1":
    #     train_func, test_func = cliff_menu()
    # elif game_choice == "2":
    #     train_func, test_func = taxi_menu()
    # else:
    #     print("Invalid game choice. Exiting.")
    #     sys.exit()
    if game_choice == "1":
          train_func, test_func = cliff_menu()
    elif game_choice == "2":
          train_func, test_func = taxi_menu()
    elif game_choice == "3":
          train_func, test_func = blackjack_menu()
    elif game_choice == "4":
          train_func, test_func = mountaincar_menu()
    else:
          print("Invalid game choice. Exiting.")
          sys.exit()

    if operation == "1":
        print("\nStarting training...")
        train_func()
    else:
        print("\nStarting testing...")
        test_func()

if __name__ == "__main__":
    main()